env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:flowtype/recommended'
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - flowtypes
rules:
  semi:
    - 2
    - always
settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true
